export const fallbackMenuItems = [
  {
    id: "fallback-antipasti-lingua",
    categoria: "antipasti",
    nome: "Lingua Salmistrata",
    descrizione: "Con salsa verde, salsa tonnata e gel al lime",
    prezzo: 18,
    disponibile: true,
    ordine: 10,
  },
  {
    id: "fallback-antipasti-uovo",
    categoria: "antipasti",
    nome: "L'Uovo al Purgatorio",
    descrizione: "Uovo bio, fonduta di Parmigiano Reggiano, olio al basilico e crostone di pane",
    prezzo: 12,
    disponibile: true,
    ordine: 20,
  },
  {
    id: "fallback-antipasti-tacos-fusion",
    categoria: "antipasti",
    nome: "Tacos Fusion",
    descrizione: "Pulled pork artigianale, guacamole e crème fraîche all'erba cipollina",
    prezzo: 16,
    disponibile: true,
    ordine: 30,
  },
  {
    id: "fallback-antipasti-tacos-summer",
    categoria: "antipasti",
    nome: "Tacos Summer",
    descrizione: "Tartare di tonno, guacamole, crème fraîche all'erba cipollina e gel al mojito",
    prezzo: 16,
    disponibile: true,
    ordine: 40,
  },
  {
    id: "fallback-antipasti-chianina",
    categoria: "antipasti",
    nome: "La Chianina",
    descrizione: "Battuta al coltello di pura Chianina e i suoi condimenti classici",
    prezzo: 16,
    disponibile: true,
    ordine: 50,
  },
  {
    id: "fallback-antipasti-fresco",
    categoria: "antipasti",
    nome: "Il Fresco",
    descrizione: "Frittino di mare del giorno secondo mercato",
    prezzo: 14,
    disponibile: true,
    ordine: 60,
  },
  {
    id: "fallback-antipasti-riso",
    categoria: "antipasti",
    nome: "Riso al Salto",
    descrizione: "Riso cacio e pepe croccante, tartare di gambero blu, gel al mango e teriyaki",
    prezzo: 17,
    disponibile: true,
    ordine: 70,
  },
  {
    id: "fallback-primi-baccala",
    categoria: "primi",
    nome: "Ricordo di Baccalà",
    descrizione: "Cappellacci fatti a mano con ripieno di baccalà marinato",
    prezzo: 19,
    disponibile: true,
    ordine: 10,
  },
  {
    id: "fallback-primi-quaglia",
    categoria: "primi",
    nome: "Bottoni alla Quaglia",
    descrizione: "Ripieni di quaglia su crema di provola affumicata e il suo fondo",
    prezzo: 18,
    disponibile: true,
    ordine: 20,
  },
  {
    id: "fallback-primi-tradizione",
    categoria: "primi",
    nome: "La Tradizione",
    descrizione: "Lasagnette verdi stordellata con il tipico ripieno dei tordelli alla carrarese",
    prezzo: 15,
    disponibile: true,
    ordine: 30,
  },
  {
    id: "fallback-primi-cacciagione",
    categoria: "primi",
    nome: "Cacciagione",
    descrizione: "Pappardelle al cervo",
    prezzo: 18,
    disponibile: true,
    ordine: 40,
  },
  {
    id: "fallback-primi-mare-terra",
    categoria: "primi",
    nome: "Mare e Terra",
    descrizione: "Ravioli del plin ai gamberi e lardo di Colonnata su crema di asparagi",
    prezzo: 20,
    disponibile: true,
    ordine: 50,
  },
  {
    id: "fallback-primi-spaghetto",
    categoria: "primi",
    nome: "Lo Spaghetto",
    descrizione: "Monograno Felicetti, vongole veraci sgusciate, zest di limone e bottarga",
    prezzo: 25,
    disponibile: true,
    ordine: 60,
  },
  {
    id: "fallback-secondi-polpo",
    categoria: "secondi",
    nome: "Il Polpo",
    descrizione: "In doppia cottura su crema di patate al limone, cipolla croccante e maionese",
    prezzo: 22,
    disponibile: true,
    ordine: 10,
  },
  {
    id: "fallback-secondi-pollo",
    categoria: "secondi",
    nome: "Pollo alla Birra",
    descrizione: "Ripieno di verdure e salsiccia con patate duchesse",
    prezzo: 17,
    disponibile: true,
    ordine: 20,
  },
  {
    id: "fallback-secondi-vaporata",
    categoria: "secondi",
    nome: "La Vaporata",
    descrizione: "Calamari e gamberi al vapore con verdurine marinate",
    prezzo: 20,
    disponibile: true,
    ordine: 30,
  },
  {
    id: "fallback-secondi-agnello",
    categoria: "secondi",
    nome: "L'Agnello",
    descrizione: "Costolette alle erbe di montagna, patate novelle e fondo bruno",
    prezzo: 25,
    disponibile: true,
    ordine: 40,
  },
  {
    id: "fallback-secondi-piccione",
    categoria: "secondi",
    nome: "Il Nostro Piccione",
    descrizione: "Con crema di carote, radicchio e il suo fondo",
    prezzo: 24,
    disponibile: true,
    ordine: 50,
  },
];

